Task/update from upstream
quandoo/intercom_flutter pull request #8
Opened 2023-02-02 13:02 UTC by mariopepe

2023-02-03 09:55 UTC, lifedemons requested changes

2023-02-03 09:55 UTC, lifedemons commented on intercom_flutter_platform_interface/CHANGELOG.md
> +>>>>>>> origin/master
@mariopepe this doesn't look good, these are the leftovers from the merge, so we need in ideal case to remerge it

2023-02-03 09:55 UTC, lifedemons commented on intercom_flutter_platform_interface/pubspec.yaml
> +<<<<<<< HEAD
same here

2023-02-03 09:55 UTC, lifedemons commented on intercom_flutter_web/CHANGELOG.md
> +=======
and here

2023-02-03 14:24 UTC, mariopepe commented on intercom_flutter_platform_interface/CHANGELOG.md
> +>>>>>>> origin/master
I already solved them yesterday, but forgot to push.

Actually i pushed, but wrongly, the right command was the one you gave me:

git push quandoo quandoo_master:task/update_from_upstream

2023-02-06 09:57 UTC, lifedemons approved these changes

2023-02-06 10:35 UTC, merged